//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvccrud.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Student
    {
        public int id { get; set; }

        [Required(ErrorMessage = "Required")]
        public string name { get; set; }

        [Required(ErrorMessage ="Required")]
        public string fname { get; set; }

        [Required(ErrorMessage = "Required")]
        [EmailAddress]
        public string email { get; set; }

        [Required(ErrorMessage = "Required")]
        [MinLength(11,ErrorMessage ="mob num should be 11 digit")]
        public string mobile { get; set; }

        public string description { get; set; }
    }
}
